- name: Configure device
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: CREATE DEVICE IN NSO
      cisco.nso.nso_config:
        url: https://10.10.20.49/jsonrpc
        username: developer
        password: C1sco12345
        data:
          tailf-ncs:devices:
            device:
            - address: 10.10.20.176
              description: CONFIGURED BY ANSIBLE!
              name: dist-rtr02
              authgroup: "labadmin"
              device-type:
                cli:
                  ned-id: "cisco-ios-cli-6.90"
              port: "22"
              state:
                admin-state: "unlocked"
      ignore_errors: yes 

    - name: DISPLAY DEVICE INCLUDING OPERATIONAL DATA
      cisco.nso.nso_show:
        url: https://10.10.20.49/jsonrpc
        username: developer
        password: C1sco12345
        path: /ncs:devices/device{dist-rtr01}
        operational: true
      register: result

    - name: Display the result
      debug:
        var: result