- name: Query devices
  hosts: nso
  connection: local
  gather_facts: no
  vars:
   devices: 
    - dist-rtr01
    - dist-rtr02

  tasks:    
    - name: DISPLAY DEVICE INCLUDING OPERATIONAL DATA
      cisco.nso.nso_show:
        url: "{{ url }}"
        username: "{{ username }}"
        password: "{{ password }}"
        path: /ncs:devices/device{dist-rtr01}
        operational: true
      register: result
      loop: "{{ devices }}"

    - name: Display the result
      debug:
        var: result

    - name: DISPLAY INTERFACES
      cisco.nso.nso_show:
        url: "{{ url }}"
        username: "{{ username }}"
        password: "{{ password }}"
        path: /ncs:devices/device{'{{item}}'}/config/interface
        operational: true
      register: result
      loop: "{{ devices }}"

    - name: Display the result
      debug:
        var: result